name: fcm
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: any
  flutter_local_notifications: any