name: fcm_config
description: This flutter package is made to merge between firebase_messaging package and flutter_local_notifications
version: 3.5.3

homepage: https://github.com/mo-ah-dawood/fcm_config/tree/master/fcm_config

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^4.0.0

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/web/firebase-messaging-sw.js
  - /example/lib/firebase_options.dart
  - /example/web/index.html
