name: fcm_config
description: This flutter package is made to merge between firebase_messaging package and flutter_local_notifications 
version: 3.1.3

homepage: https://github.com/mo-ah-dawood/fcm_config/tree/master/fcm_config

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  flutter_local_notifications: ^9.0.1
  http: ^0.13.4
  path_provider: ^2.0.5

dev_dependencies:
  pedantic: ^1.11.0
